package org.mobicents.slee.container.deployment;

import java.io.File;
import java.io.IOException;

import javax.slee.management.DeploymentException;

import org.apache.log4j.Logger;

import javassist.CannotCompileException;
import javassist.CtClass;

/**
 * Solution A (optimizejainsleep2.md): persist Javassist output to disk at deploy-time
 * and load through the deployment class loader. Never call {@link CtClass#toClass()}.
 */
public final class JavassistDeployTimeCodegen {

    public static final String OUTPUT_DIR_PROPERTY = "jainslee.codegen.output.dir";

    private static final Logger logger = Logger.getLogger(JavassistDeployTimeCodegen.class);

    private JavassistDeployTimeCodegen() {
    }

    public static File resolveOutputDir(String deployDir) {
        String override = System.getProperty(OUTPUT_DIR_PROPERTY);
        if (override != null && override.trim().length() > 0) {
            return new File(override.trim());
        }
        return new File(deployDir);
    }

    /**
     * Writes {@code ctClass} bytecode under {@code deployDir} (or global override dir).
     */
    public static void persist(CtClass ctClass, String deployDir) throws CannotCompileException, IOException {
        File outputDir = resolveOutputDir(deployDir);
        if (!outputDir.exists() && !outputDir.mkdirs()) {
            throw new IOException("Unable to create codegen output directory: " + outputDir);
        }
        ctClass.writeFile(outputDir.getAbsolutePath());
        if (logger.isDebugEnabled()) {
            logger.debug("Persisted generated class " + ctClass.getName() + " under " + outputDir.getAbsolutePath());
        }
    }

    /**
     * Persists generated bytecode then loads it from the supplied class loader.
     */
    public static Class<?> persistAndLoad(CtClass ctClass, String deployDir, ClassLoader classLoader)
            throws DeploymentException {
        if (classLoader == null) {
            throw new DeploymentException("ClassLoader must not be null when loading generated class "
                    + ctClass.getName());
        }
        try {
            persist(ctClass, deployDir);
            return classLoader.loadClass(ctClass.getName());
        } catch (CannotCompileException e) {
            throw new DeploymentException("Failed to compile generated class " + ctClass.getName(), e);
        } catch (IOException e) {
            throw new DeploymentException("Failed to write generated class " + ctClass.getName(), e);
        } catch (ClassNotFoundException e) {
            throw new DeploymentException("Generated class not found after writeFile: " + ctClass.getName(), e);
        }
    }

    public static Class<?> persistAndLoad(CtClass ctClass, String deployDir) throws DeploymentException {
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        return persistAndLoad(ctClass, deployDir, classLoader);
    }
}
