quarkus.application.name=ussd-quarkus-demo
quarkus.http.port=8080

microjainslee.buffer-size=2048
microjainslee.prefer-virtual-threads=true
microjainslee.sbb-pool-min=16
microjainslee.sbb-pool-max=4096
microjainslee.sbb-per-virtual-thread=true
microjainslee.deployment.scan.enabled=true
microjainslee.deployment.scan.includes=com.example.ussddemo

ussd.demo.grpc.latency-ms=50
ussd.demo.session-timeout-seconds=30
