/*
 * micro-jainslee 1.2.0
 *
 * Dual-licensed: GPLv3 (Section A) OR Commercial License (Section B).
 * See the LICENSE file at the root of this repository for the full text.
 *
 * Copyright (c) 2026 Tran Nhan (nhanth87). All rights reserved.
 * Contact: nhanth87@gmail.com
 */

package com.microjainslee.apt;

import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Emits compile-time {@code $OffHeapConcrete} subclasses for abstract
 * {@code @OffHeap} SBBs — same accessor shape as deploy-time
 * {@code ConcreteSbbGenerator}, using {@code OffHeapCmpAccessor}.
 */
final class OffHeapConcreteEmitter {

    private OffHeapConcreteEmitter() {
    }

    record CmpAccessor(String fieldName, String methodName, boolean setter,
                       String javaType, boolean isGetter) {
    }

    static void emit(TypeElement abstractSbb, Filer filer, Messager messager) throws IOException {
        // Nested types (e.g. test fixtures inside FooTest) cannot host a sibling
        // $OffHeapConcrete without clashing with the enclosing class name as a package.
        if (abstractSbb.getNestingKind() != javax.lang.model.element.NestingKind.TOP_LEVEL) {
            messager.printMessage(Diagnostic.Kind.NOTE,
                    "[micro-jainslee] @OffHeap nested type " + abstractSbb.getQualifiedName()
                            + " — skip APT $OffHeapConcrete (use ConcreteSbbGenerator / top-level SBB)");
            return;
        }

        if (!abstractSbb.getModifiers().contains(Modifier.ABSTRACT)
                && !hasAbstractCmpMethods(abstractSbb)) {
            messager.printMessage(Diagnostic.Kind.NOTE,
                    "[micro-jainslee] @OffHeap on non-abstract " + abstractSbb.getQualifiedName()
                            + " — skip $OffHeapConcrete (hand-written OffHeapBindable expected)");
            return;
        }

        String abstractFqn = abstractSbb.getQualifiedName().toString();
        String pkg = packageName(abstractFqn);
        String simple = abstractSbb.getSimpleName().toString();
        String concreteSimple = simple + "$OffHeapConcrete";
        String concreteFqn = pkg.isEmpty() ? concreteSimple : pkg + "." + concreteSimple;

        List<CmpAccessor> accessors = collectAccessors(abstractSbb);
        if (accessors.isEmpty()) {
            messager.printMessage(Diagnostic.Kind.ERROR,
                    "@OffHeap SBB " + abstractFqn + " declares no @CmpField accessors",
                    abstractSbb);
            return;
        }

        // Preserve declaration order of unique field names for layout notes.
        Map<String, String> fieldTypes = new LinkedHashMap<>();
        for (CmpAccessor a : accessors) {
            fieldTypes.putIfAbsent(a.fieldName(), a.javaType());
        }

        StringBuilder body = new StringBuilder();
        body.append("/*\n");
        body.append(" * Generated by micro-jainslee OffHeapConcreteEmitter — do not edit.\n");
        body.append(" */\n\n");
        if (!pkg.isEmpty()) {
            body.append("package ").append(pkg).append(";\n\n");
        }
        body.append("import com.microjainslee.api.OffHeapBindable;\n");
        body.append("import com.microjainslee.core.offheap.OffHeapCmpAccessor;\n");
        body.append("import com.microjainslee.core.offheap.OffHeapLayout;\n");
        body.append("import com.microjainslee.core.offheap.OffHeapRuntime;\n\n");
        body.append("/**\n");
        body.append(" * Compile-time off-heap concrete for {@link ").append(simple).append("}.\n");
        body.append(" * Deploy-time Javassist {@code $Concrete} remains the default pool path;\n");
        body.append(" * this class is the APT Production-2 gate for zero-Map CMP accessors.\n");
        body.append(" */\n");
        body.append("public final class ").append(concreteSimple)
                .append(" extends ").append(simple)
                .append(" implements OffHeapBindable {\n\n");
        body.append("    private static volatile OffHeapLayout _OHL;\n");
        body.append("    private volatile long _offHeapBase;\n");
        body.append("    private volatile String _entityId;\n\n");

        for (String field : fieldTypes.keySet()) {
            body.append("    private static volatile int _ohIdx_").append(field).append(" = -1;\n");
        }
        body.append('\n');

        body.append("    private static OffHeapLayout _ohl() {\n");
        body.append("        OffHeapLayout l = _OHL;\n");
        body.append("        if (l == null) {\n");
        body.append("            l = OffHeapRuntime.layoutFor(").append(simple).append(".class);\n");
        body.append("            _OHL = l;\n");
        body.append("        }\n");
        body.append("        return l;\n");
        body.append("    }\n\n");

        body.append("    @Override public void bindSlot(long baseAddr) { this._offHeapBase = baseAddr; }\n");
        body.append("    @Override public void unbindSlot() { this._offHeapBase = 0L; }\n");
        body.append("    @Override public void setEntityId(String entityId) { this._entityId = entityId; }\n");
        body.append("    @Override public long slotAddress() { return this._offHeapBase; }\n\n");

        Set<String> emitted = new java.util.HashSet<>();
        for (CmpAccessor a : accessors) {
            String key = a.methodName() + "#" + a.setter();
            if (!emitted.add(key)) {
                continue;
            }
            emitMethod(body, a);
        }

        body.append("}\n");

        JavaFileObject source = filer.createSourceFile(concreteFqn, abstractSbb);
        try (Writer w = source.openWriter()) {
            w.write(body.toString());
        }
        messager.printMessage(Diagnostic.Kind.NOTE,
                "[micro-jainslee] Wrote " + concreteFqn + " (" + fieldTypes.size() + " CMP fields)");
    }

    private static void emitMethod(StringBuilder body, CmpAccessor a) {
        String acc = "OffHeapCmpAccessor";
        String prologue =
                "        OffHeapLayout l = _ohl();\n"
                + "        long b = this._offHeapBase;\n"
                + "        int i = _ohIdx_" + a.fieldName() + ";\n"
                + "        if (i < 0) { i = l.indexOf(\"" + a.fieldName() + "\"); _ohIdx_"
                + a.fieldName() + " = i; }\n";

        if (a.setter()) {
            body.append("    @Override\n");
            body.append("    public void ").append(a.methodName()).append('(')
                    .append(a.javaType()).append(" v) {\n");
            body.append(prologue);
            body.append("        ").append(writeCall(acc, a.javaType())).append(";\n");
            body.append("    }\n\n");
        } else {
            body.append("    @Override\n");
            body.append("    public ").append(a.javaType()).append(' ')
                    .append(a.methodName()).append("() {\n");
            body.append(prologue);
            body.append("        return ").append(readCall(acc, a.javaType())).append(";\n");
            body.append("    }\n\n");
        }
    }

    private static String readCall(String acc, String javaType) {
        return switch (javaType) {
            case "int" -> acc + ".readInt(l, b, i)";
            case "long" -> acc + ".readLong(l, b, i)";
            case "boolean" -> acc + ".readBoolean(l, b, i)";
            case "double" -> acc + ".readDouble(l, b, i)";
            case "java.lang.String", "String" -> acc + ".readString(l, b, i)";
            case "byte[]" -> acc + ".readBytes(l, b, i)";
            default -> throw new IllegalArgumentException("unsupported off-heap type: " + javaType);
        };
    }

    private static String writeCall(String acc, String javaType) {
        return switch (javaType) {
            case "int" -> acc + ".writeInt(l, b, i, v)";
            case "long" -> acc + ".writeLong(l, b, i, v)";
            case "boolean" -> acc + ".writeBoolean(l, b, i, v)";
            case "double" -> acc + ".writeDouble(l, b, i, v)";
            case "java.lang.String", "String" -> acc + ".writeString(l, b, i, v)";
            case "byte[]" -> acc + ".writeBytes(l, b, i, v)";
            default -> throw new IllegalArgumentException("unsupported off-heap type: " + javaType);
        };
    }

    private static boolean hasAbstractCmpMethods(TypeElement te) {
        for (Element e : te.getEnclosedElements()) {
            if (e.getKind() == ElementKind.METHOD
                    && e.getModifiers().contains(Modifier.ABSTRACT)
                    && hasCmpField(e)) {
                return true;
            }
        }
        return false;
    }

    private static List<CmpAccessor> collectAccessors(TypeElement te) {
        List<CmpAccessor> out = new ArrayList<>();
        for (Element e : te.getEnclosedElements()) {
            if (e.getKind() != ElementKind.METHOD || !(e instanceof ExecutableElement ee)) {
                continue;
            }
            if (!hasCmpField(e)) {
                continue;
            }
            String fieldName = cmpFieldName(e);
            String method = ee.getSimpleName().toString();
            boolean setter = method.startsWith("set") || ee.getParameters().size() == 1;
            String javaType;
            if (setter) {
                if (ee.getParameters().isEmpty()) {
                    continue;
                }
                javaType = typeName(ee.getParameters().get(0).asType());
            } else {
                javaType = typeName(ee.getReturnType());
            }
            out.add(new CmpAccessor(fieldName, method, setter, javaType, !setter));
        }
        return out;
    }

    private static boolean hasCmpField(Element e) {
        return e.getAnnotationMirrors().stream().anyMatch(m ->
                m.getAnnotationType().toString().equals(
                        "com.microjainslee.api.annotations.CmpField"));
    }

    private static String cmpFieldName(Element e) {
        var ann = e.getAnnotation(com.microjainslee.api.annotations.CmpField.class);
        if (ann != null && ann.value() != null && !ann.value().isBlank()) {
            return ann.value();
        }
        String method = e.getSimpleName().toString();
        if (method.startsWith("get") && method.length() > 3) {
            return Character.toLowerCase(method.charAt(3)) + method.substring(4);
        }
        if (method.startsWith("set") && method.length() > 3) {
            return Character.toLowerCase(method.charAt(3)) + method.substring(4);
        }
        if (method.startsWith("is") && method.length() > 2) {
            return Character.toLowerCase(method.charAt(2)) + method.substring(3);
        }
        return method;
    }

    private static String typeName(TypeMirror tm) {
        if (tm.getKind().isPrimitive()) {
            return tm.toString();
        }
        if (tm.getKind() == TypeKind.ARRAY) {
            return tm.toString();
        }
        String s = tm.toString();
        if ("java.lang.String".equals(s)) {
            return "String";
        }
        return s;
    }

    private static String packageName(String fqn) {
        int dot = fqn.lastIndexOf('.');
        return dot >= 0 ? fqn.substring(0, dot) : "";
    }
}
